"""Auditable selected CAR variants. Build data only; no commands are executed."""
def leaf(op, field, value): return [op, field, value]
def allof(*items): return ["all", *items]
def anyof(*items): return ["any", *items]
def image(*names): return leaf("basename", "Image", list(names))
def parent(*names): return leaf("basename", "ParentImage", list(names))
def tok(*words): return leaf("tokens_any", "CommandLine", list(words))
def toks(*words): return allof(*(tok(w) for w in words))
def glob(field, *patterns): return leaf("glob", field, list(patterns))
def neq(field, *values): return leaf("not_equal", field, list(values))
def rg(field, pattern): return leaf("regex", field, pattern)
def pathval(*patterns): return glob("TargetObject", *patterns)
SPECS = {}
def add(cid, category, condition, variant="selected upstream process/event pattern", ids=None):
    SPECS.setdefault("CAR-"+cid, []).append({"category": category, "condition": condition,
        "variant": variant, "attack_ids_override": ids})
P="process_creation"; R="registry_set"; F="file_event"
add("2013-02-003",P,image("cmd.exe"),ids=["T1059.003"])
add("2013-05-002",P,glob("Image",r"*:\recycler\*",r"*:\systemvolumeinformation\*",r"*:\system volume information\*",r"c:\windows\tasks\*",r"c:\windows\debug\*"))
add("2013-05-004",P,image("at.exe"))
add("2013-07-005",P,tok("a"),"upstream archiving-argument monitor; archive creation and intent unproven")
add("2013-08-001",P,image("schtasks.exe"))
add("2013-10-002","create_remote_thread",allof(leaf("equal","StartFunction",["LoadLibraryA","LoadLibraryW"]),leaf("different_pid","SourceProcessId","TargetProcessId")),
    "LoadLibrary remote-thread variant; analyzed source only, distinct explicit PIDs; no UAC claim",["T1055.001"])
add("2014-03-006",P,image("rundll32.exe"))
add("2014-04-003",P,allof(image("powershell.exe"),leaf("not_basename","ParentImage",["explorer.exe"])),ids=["T1059.001"])
add("2014-05-002",P,allof(image("cmd.exe"),parent("services.exe")))
add("2014-11-004",P,allof(image("wsmprovhost.exe"),parent("svchost.exe")))
add("2014-11-006","network_connection",leaf("integer","DestinationPort",[5985,5986]),"port monitor on attributed sample traffic; session/authentication unproven")
add("2014-11-008",P,allof(image("cmd.exe"),parent("winlogon.exe")))
add("2016-03-001",P,anyof(image("hostname.exe","ipconfig.exe","net.exe","quser.exe","qwinsta.exe","systeminfo.exe","tasklist.exe","whoami.exe"),allof(image("sc.exe"),leaf("first_arg","CommandLine",["query","qc"]))),
    "command monitor; ATT&CK tags restricted to actual command operation",[])
add("2016-03-002",P,allof(image("wmic.exe"),toks("process","call","create"),rg("CommandLine",r"(?i)(?:^|\s)/node:\S+")))
add("2019-04-002",P,allof(parent("regsvr32.exe"),leaf("not_basename","Image",["regsvr32.exe"])),
    "spawning-child-process variant only; baseline and unsigned-image variants not implemented")
add("2019-04-003",P,allof(image("regsvr32.exe"),rg("CommandLine",r"(?i)(?:^|[\s\\])scrobj\.dll(?:$|[\s\"])")))
add("2019-07-002",P,allof(glob("Image",r"*\procdump*.exe"),rg("CommandLine",r"(?i)\blsass(?:\.exe)?\b")),
    "process-create variant only; process-access variant requires extra fields",["T1003.001"])
add("2019-08-001",F,allof(glob("Image",r"c:\windows\*\taskmgr.exe"),glob("TargetFilename",r"*\lsass*.dmp")),
    "Task Manager file-create pattern; dump contents unverified",["T1003.001"])
add("2019-08-002",F,allof(image("ntdsutil.exe"),leaf("basename","TargetFilename",["ntds.dit"])))
add("2020-09-001",F,allof(glob("TargetFilename",r"c:\windows\system32\tasks\*",r"c:\windows\tasks\*"),neq("Image",r"c:\windows\system32\svchost.exe")))
add("2020-09-002","registry_event",pathval(r"*\software\classes\clsid\*"),"observed registry modification pattern; hijack execution not proven")
add("2020-09-003",P,allof(image("fltmc.exe"),leaf("first_arg","CommandLine",["unload"])))
add("2020-09-005","registry_event",rg("TargetObject",r"(?i)\\software\\(?:wow6432node\\)?microsoft\\windows nt\\currentversion\\windows\\appinit_dlls(?:\\|$)"))
add("2020-11-001",R,pathval(r"*\environment\userinitmprlogonscript"),"registry-write variant only")
add("2020-11-002",P,anyof(image("tshark.exe","windump.exe","tcpdump.exe","wprui.exe","wpr.exe"),allof(image("logman.exe"),neq("ParentImage",r"c:\program files\windows event reporting\core\eventreporting.agentservice.exe"))))
add("2020-11-003",P,allof(image("mavinject.exe"),tok("/injectrunning")),"narrowed executable + injectrunning arguments; not arbitrary command text",["T1055.001"])
add("2020-11-004",P,leaf("irregular_parent","Image","ParentImage"))
add("2020-11-006",P,allof(image("net.exe"),leaf("first_arg","CommandLine",["user","group","localgroup"])),"net operation monitor; no assertion of malicious intent",[])
add("2020-11-007",P,allof(image("net.exe"),leaf("first_arg","CommandLine",["use","share"]),tok("/delete")),"narrowed net share-removal command variant")
add("2020-11-008",P,glob("Image",r"c:\windows\microsoft.net\framework*\msbuild.exe",r"c:\users\*\appdata\roaming\microsoft\msxsl.exe"))
add("2020-11-009",P,glob("Image",r"c:\windows\system32\hh.exe",r"c:\windows\syswow64\hh.exe"))
add("2020-11-011",R,pathval(r"*\software\policies\microsoft\windows\control panel\desktop\scrnsave.exe"))
add("2021-01-003",P,allof(image("wevtutil.exe"),leaf("first_arg","CommandLine",["cl","clear-log"]),tok("system","security","setup","application")),"process command variant; successful log deletion requires event confirmation")
add("2021-01-006",P,allof(parent("excel.exe","word.exe","winword.exe","outlook.exe"),glob("Image",r"*.exe")),"broad Office-child monitor; DDE exploitation not established")
add("2021-01-007",P,allof(glob("Image",r"c:\windows\system32\sc.exe"),leaf("first_arg","CommandLine",["config","stop","query"])),"upstream sc monitor includes query; tampering not established",[])
add("2021-01-009",P,anyof(allof(image("vssadmin.exe"),anyof(toks("delete","shadows"),toks("resize","shadowstorage"))),allof(image("wmic.exe"),toks("shadowcopy","delete"))),"process-command variant only; WMI event variants not implemented")
add("2021-02-001",P,allof(leaf("basename_glob","ParentImage",["w3wp.exe","httpd.exe","tomcat*.exe","nginx.exe"]),image("cmd.exe","powershell.exe","net.exe","whoami.exe","hostname.exe","systeminfo.exe","ipconfig.exe")))
add("2021-02-002",P,allof(parent("services.exe"),image("cmd.exe"),tok("echo"),rg("CommandLine",r"(?i)\\pipe\\")),"service-child echo-to-pipe variant only; elevation success unproven")
add("2021-04-001",P,leaf("masquerade_system_path","Image",True),"corrected upstream OR/typo; both legitimate System32 and SysWOW64 paths excluded")
add("2021-05-001",P,allof(glob("Image",r"c:\windows\system32\certutil.exe"),tok("-addstore")),"certificate-store command monitor; trust change unproven")
add("2021-05-002",F,glob("TargetFilename",r"c:\windows\system32\*.bat"))
add("2021-05-003",P,allof(glob("Image",r"c:\windows\system32\bcdedit.exe"),tok("recoveryenabled")),"upstream recovery configuration monitor; enable and disable need analyst interpretation")
add("2021-05-004",P,allof(glob("Image",r"c:\windows\system32\bitsadmin.exe"),tok("/create","/addfile","/setnotifyflags","/setnotifycmdline","/setminretrydelay","/setcustomheaders","/resume")))
add("2021-05-005",P,allof(glob("Image",r"c:\windows\system32\bitsadmin.exe"),tok("/transfer")))
add("2021-05-006",P,allof(glob("Image",r"c:\windows\system32\certutil.exe"),toks("-urlcache","-split")))
add("2021-05-007",P,allof(glob("Image",r"c:\windows\system32\certutil.exe"),toks("-verifyctl","-split")))
add("2021-05-008",P,allof(glob("Image",r"c:\windows\system32\certutil.exe"),tok("-exportpfx")))
add("2021-05-009",P,allof(glob("Image",r"c:\windows\system32\certutil.exe"),tok("-decode","-decodehex")))
add("2021-05-010",P,allof(image("net.exe","net1.exe"),leaf("first_arg","CommandLine",["user","localgroup"]),tok("/add")),"narrowed add-operation variant; local administrator membership not inferred from user creation",[])
add("2021-05-011","create_remote_thread",allof(leaf("basename","TargetImage",["lsass.exe"]),leaf("different_pid","SourceProcessId","TargetProcessId")),"target-bound remote thread; dump content and credential theft unproven",["T1055"])
add("2021-11-001",R,allof(pathval(r"*\system\currentcontrolset\control\session manager\safedllsearchmode",r"*\system\controlset00?\control\session manager\safedllsearchmode"),leaf("dword","Details",[0])),"registry value variant only")
add("2021-11-002",R,pathval(r"*\microsoft\windows nt\currentversion\winlogon\userinit",r"*\microsoft\windows nt\currentversion\winlogon\shell",r"*\microsoft\windows nt\currentversion\winlogon\notify*"),"registry value variant with Winlogon path boundary")
add("2021-12-001",P,allof(image("schtasks.exe"),tok("/create","/change"),tok("/tr"),rg("CommandLine",r"(?i)\.(?:cmd|ps1|vbs|py|js|exe|bat)\b")),"task command variant for executable/script extensions; successful registration unproven")
add("2021-12-002",R,pathval(r"*\microsoft\windows\currentversion\explorer\user shell folders\common startup",r"*\microsoft\windows\currentversion\explorer\shell folders\common startup"),"registry value variant with Startup-folder key boundary")
add("2022-03-001",R,allof(pathval(r"*\system\currentcontrolset\services\eventlog\start",r"*\system\controlset00?\services\eventlog\start"),leaf("dword","Details",[4])),"registry disable-start variant only; remaining command variants deferred")
